# Utilities for a target
[armv7-unknown-linux-gnueabihf]
linker = "C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-gcc"
cmake_toolchain_file = """
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_FLAGS "-mcpu=cortex-a7 -mfpu=neon-vfpv4 -fPIC")
"""

# Env vars for a target
[armv7-unknown-linux-gnueabihf.env]
PERL = "C:/Users/nathaniel/scoop/apps/msys2/current/usr/bin/perl" 

CC = "C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-gcc"
CXX = "C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-g++"

CMAKE_GENERATOR = "Ninja"

[aarch64-unknown-linux-gnu]
linker = "C:/SysGCC/raspberry64/bin/aarch64-linux-gnu-gcc"
cmake_toolchain_file = """
set(CMAKE_SYSTEM_NAME Linux)
"""

[aarch64-unknown-linux-gnu.env]
CC = "C:/SysGCC/raspberry64/bin/aarch64-linux-gnu-gcc"
CXX = "C:/SysGCC/raspberry64/bin/aarch64-linux-gnu-g++"

CMAKE_GENERATOR = "Ninja"