[package]
name = "rust-raspberry-pi"
version = "0.0.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]

[target.'cfg(all(any(target_arch = "arm", target_arch = "aarch64"), target_os = "linux"))'.dependencies]
once_cell = "1.12.0"
thiserror = "1.0.31"

[features]
default = []