name: RustDoc
on:
  push:
   branches:
   - master
jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src
        
    - name: Install AARCH64 target
      run: rustup target add aarch64-unknown-linux-gnu
        
    # TODO : Support multi-target
    - name: Build Documentation
      run: cargo doc --all --no-deps --target aarch64-unknown-linux-gnu
      
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
